name: vprofile actions

on: 
  workflow_dispatch

env:
  AWS_REGION: us-east-1                     # AWS region for resources
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-new-eks                 # EKS cluster name

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'           # Use Eclipse Temurin distribution
          java-version: '11'                # Set Java version to 11

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Maven Test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src \
            -Dsonar.junit.reportPaths=target/surefire-reports \
            -Dsonar.jacoco.reportPaths=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=**/target/classes

      - name: SonarQube Quality Gate Check
        id: sonarqube-quality-gate-check
        uses: SonarSource/sonar-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          timeout-minutes: 5 # Timeout in minutes (e.g., 5 minutes)
